name: CI
on:
    push:
        branches:
            - master
    pull_request:
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: install dependencies
              run: npm ci --quiet
            - name: lint ts
              run: npm run lint:ts
            - name: compile typescript
              run: npm run typecheck
            - name: run tests
              run: npm test
